### ISSUE TITLE
Audio Routing settings - DAW channel per DMG channel

### ISSUE THREAD

**Issue by r4dian** [tommitytom/RetroPlug#26]
I guess it depends on the emulator in use here, but would it be possible to have the DMG's channels 1-4 separately on the 4 VST outputs ?

**Comment by tommitytom** [comment]
I've made a proof of concept of this but it was a bit buggy so never added it to the main build, but it's definitely possible.  I wanted to implement it without making any changes to sameboy.  The thing is, Sameboy applies DC offets, filters, etc to the already summed channel output, rather than each individual channel, so I need to add those processing steps myself if channels are split.  I'm sure I'll look in to it again soon as it's a quite often requested feature, so I'll leave this issue open.

Also, it's worth noting that each channel is stereo, so it would actually map DMG channels 1-4 to VST channels 1-8.

**Comment by r4dian** [comment]
Ah yeah sorry for confusion, my DAW groups 1-8 as 4 stereo output tracks by default.

**Comment by ftsf** [comment]
You can emulate this by duplicating the project 4 times and soloing each channel, using midi sync+autoplay to start them all at once, routing each system to a single stereo output.

**Comment by r4dian** [comment]
Oh damn, right. Thanks.
