### ISSUE TITLE
Suggestion: Add support for Vice emu

### ISSUE THREAD

**Issue by kiwanowski** [tommitytom/RetroPlug#5]
Hello, Ive seen in the readme file that you are thinking about adding support for the GBA and Genesis. I dont really understand why, but it would be awesome if you could add support for VICE so we could use defmon http://toolsforscholars.com/defmon/doku.php with RetroPlug

**Comment by tommitytom** [comment]
I intended to add GBA and Genesis support because they both have some form of MIDI interface (https://catskullelectronics.com/gbamidi and https://catskullelectronics.com/genmdm).  When I initially started building this, it began as a libretro frontend so it would support any emulator that RetroArch supported.  However there are limitations to libretro that mean multiple instances of the VST can't be run in a DAW, and also lacked interfaces for serial port access so I ended up having to modify it anyway!  I may try and fix up libretro support in the future so you'll be able to use defmon, but I'm afraid there will be no MIDI sync.

**Comment by kiwanowski** [comment]
Oh, I didnt know that the GenMDM rom is publicly available. Thats awesome :) Regarding VICE I think that there is no reason to support it without MIDI sync. Either way I just want to say that RetroPlug is really great and I cant wait for the MacOS version :)

**Comment by cyberic99** [comment]
> so you'll be able to use defmon, but I'm afraid there will be no MIDI sync.

Hello

I can't understand how MIDI on the C64 is different from on the gba or the Genesis.

There are multiple MIDI interfaces for the C64
(like http://www.frank-buss.de/kerberos/, https://www.c64-wiki.de/wiki/MIDI-Interface, http://www.mycommodore64.com/2011/09/09/fb-midi-a-modern-midi-interface/), and you just have to write to a specific address to send a MIDI byte.

Thinking about it, if you could allow to write to the SID chip by sending MIDI, it could be cool too.

**Comment by tommitytom** [comment]
I did notice they exist, though it would be hard for me to get hold of any of them to test against!  Additional consoles are a way off yet - I'd like to get v1 finished first, more specifically the Lua support since it would make things a lot more flexible.  I'll add C64 to the roadmap :)
